# 未填的采用默认值

APP:
  NAME: library-api
  RUNMODE: debug # 模式: debug, release, test
  ADDR: :8033 # 端口
  URL: http://localhost:8033 # 网站 url，内部跳转时会用到该项
  API_PREFIX: /api # API 前缀
  KEY: AYCmJy4cYV1H5kpobYOIOvwgYcghg8A1 # 加密 key
  TOKEN_KEY: TOKEN # header token 字段

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: library-api # 实际连接的数据库会增加 RUNMODE 后缀：xxx_debug、xxx_test 等
  USERNAME: username
  PASSWORD: secret

LOG:
  WRITERS: file,stdout # 输出位置，有两个可选项 —— file 和 stdout。选择 file 会将日志记录到 logger_file 指定的日志文件中，选择 stdout 会将日志输出到标准输出，当然也可以两者同时选择
  LOGGER_LEVEL: DEBUG # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  LOGGER_FILE: storage/logs/library-api.log # 日志文件
  LOG_FORMAT_TEXT: false # 日志的输出格式，JSON 或者 plaintext，true 会输出成 JSON 格式，false 会输出成非 JSON 格式
  ROLLING_POLICY: size # rotate 依据，可选的有 daily 和 size。如果选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  LOG_ROTATE_DATE: 1 # rotate 转存时间，配 合rollingPolicy: daily 使用
  LOG_ROTATE_SIZE: 1 # rotate 转存大小，配合 rollingPolicy: size 使用 (大于 1mb 会压缩为 zip)
  LOG_BACKUP_COUNT: 7 # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数
